server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092

    properties:
      schema:
        registry:
          url: http://localhost:8081

      specific:
        avro:
          reader: true

    listener:
      missing-topics-fatal: false
      ack-mode: MANUAL_IMMEDIATE
      concurrency: 2

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

    consumer:
      group-id: testing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

kafka:
  producer:
    topic: test-topic

  consumer:
    topic: test-topic

retry:
  consumer:
    backoff-ms: 5000
    max-attempts: 5